name: flutter_mvvm_template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  file_picker: ^5.3.1
  firebase_performance: ^0.9.2+2
  flutter_advanced_drawer: ^1.2.2
  flutter_screenutil: ^5.0.0
  flutter_svg: ^2.0.6
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  get: ^4.1.4
  get_it: ^7.1.3
  google_maps_flutter: ^2.1.5
  heic_to_jpg: ^0.2.0
  image_picker: ^0.8.0+1
  intl: ^0.18.1
  logger: ^1.0.0
  modal_progress_hud_nsn: ^0.4.0
  permission_handler: ^10.2.0
  provider: ^6.0.3
  shared_preferences: ^2.0.5
  shimmer: ^3.0.0
  url_launcher: ^6.0.7
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  google_sign_in: ^6.1.3
  flutter_facebook_auth: ^5.0.11
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  github_sign_in: ^0.0.5-dev.4
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  firebase_crashlytics: ^3.3.2
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
dependency_overrides:
  # firebase_messaging_platform_interface: 3.1.6


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
