// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vdk3n8b7ET_6y1BJ1Ke66Rl9VNY_uhs',
    appId: '1:646748873521:web:0e87789c70ab687a198610',
    messagingSenderId: '646748873521',
    projectId: 'dumy-bdc71',
    authDomain: 'dumy-bdc71.firebaseapp.com',
    storageBucket: 'dumy-bdc71.appspot.com',
    measurementId: 'G-JXRH3JMBL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX930WsFuMIZGv7fwq59RW9XOWlstCdcg',
    appId: '1:646748873521:android:e6bcf44ba0e1f524198610',
    messagingSenderId: '646748873521',
    projectId: 'dumy-bdc71',
    storageBucket: 'dumy-bdc71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFwIJ8IPImKrl9xEBa0xt-TT0X158Y5s',
    appId: '1:646748873521:ios:155abefea913d1fa198610',
    messagingSenderId: '646748873521',
    projectId: 'dumy-bdc71',
    storageBucket: 'dumy-bdc71.appspot.com',
    iosClientId: '646748873521-sl65v528d3ilf9fn9pfl83bl9s142cmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMvvmTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFwIJ8IPImKrl9xEBa0xt-TT0X158Y5s',
    appId: '1:646748873521:ios:155abefea913d1fa198610',
    messagingSenderId: '646748873521',
    projectId: 'dumy-bdc71',
    storageBucket: 'dumy-bdc71.appspot.com',
    iosClientId: '646748873521-sl65v528d3ilf9fn9pfl83bl9s142cmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMvvmTemplate',
  );
}
